export default {
  'Update': 'Оновлення',
  '{0} {1} is now available--you have {2}. Would you like to download it now?': '{0} {1} тепер доступний - у вас є {2}. Ви хочете завантажити його зараз?',
  'An error occurred while downloading the update. Please try again later.': 'Під час завантаження оновлення сталася помилка. Будь-ласка спробуйте пізніше.',
  'You already have the newest version of {0}.': 'Ви вже маєте останню версію {0}.',
  'An error occurred in retrieving update information. Please try again later.': 'Під час отримання інформації про оновлення сталася помилка. Будь-ласка спробуйте пізніше.',
  'Downloading update...': 'Завантаження оновлення...',
  'OK': 'в порядку',
  'E-Mail': 'Електронна пошта',
  'Code': 'Код',
  'Cancel': 'Скасувати',
  'Register': 'Зареєструйтесь',
  'Buy Now': 'Придбайте зараз',
  'Please enter the registration information to upgrade trial version to registered version.': 'Введіть реєстраційну інформацію, щоб оновити пробну версію до зареєстрованої.',
  'Invalid license!': 'Недійсна ліцензія!',
  'The registration information must be entered exactly as they appear in your confirmation email. Using copy and paste method to enter the license is recommended.': 'Інформацію про реєстрацію потрібно вводити точно так, як вони вказані у вашому електронному листі з підтвердженням. Для введення ліцензії рекомендується використовувати метод копіювання та вставлення.',
  'You have successfully registration the program. Thank you for your support!': 'Ви успішно зареєстрували програму. Спасибі вам за вашу підтримку!',
  'A new version of {0} is available': 'Доступна нова версія {0}',
  '{0} {1} is now available-you have {2}. Would you like to download it now?': '{0} {1} тепер доступний - у вас є {2}. Ви хочете завантажити його зараз?',
  'Skip This Version': 'Пропустити цю версію',
  'Remind Me Later': 'Нагадай мені пізніше',
  'Install Update': 'Встановити оновлення',
  'Software Update': 'Оновлення програмного забезпечення',
  'Release Notes': 'Примітки до випуску:',
  'User name': 'Ім’я користувача',
  'License to': 'Ліцензія на',
  'About': 'Про',
  'File': 'Файл',
  'Show Log File': 'Показати файл журналу',
  'Edit': 'Редагувати',
  'Cut': 'Вирізати',
  'Copy': 'Скопіювати',
  'Paste': 'Вставити',
  'Select All': 'Вибрати все',
  'Window': 'Вікно',
  'Minimize': 'Мінімізуйте',
  'Zoom': 'Збільшити',
  'Preferences': 'Переваги',
  'Hide': 'Сховати',
  'Hide Others': 'Сховати інших',
  'Quit': 'Вийдіть',
  'Help': 'Довідка',
  'Open Website': 'Відкрити веб-сайт',
  'Check for update': 'Перевірити оновлення',
  'regist successfully': 'Реєстрація завершена',
  
  'Change Account': 'Змінити рахунок',
  'Please enter your new license,': 'Будь ласка, введіть свою нову ліцензію,',
  'or buy a new one.': 'або купити новий.',
  'Confirm': 'Підтвердіть',
  'User ID': 'ідентифікатор користувача',
  'License Plan': 'Ліцензійний план',
  'Change Plan': 'План змін',
  'Expiration Date': 'Термін придатності',
  'Family license': 'Час життя',
  'One Year license': 'Обмежений часом',
  'Your license will expire soon on {0}. Please renew your license.': 'Ваша ліцензія закінчується незабаром {0}. Поновіть вашу ліцензію.',
  'Renew License': 'Поновлення ліцензії',
  'Your license has expired. Please renew your license.': 'Термін дії вашої ліцензії закінчився Поновіть вашу ліцензію.',
  'Your license has expired. Please renew your license or register with other license.':'Термін дії вашої ліцензії закінчився Поновіть свою ліцензію або зареєструйтесь з іншими ліцензіями.',
  'Your license is valid until:': 'Ваша ліцензія дійсна до:'
}
