export default {
  'Update': 'Обновить',
  '{0} {1} is now available--you have {2}. Would you like to download it now?': '{0} {1} уже доступна - у вас установлена {2}. Вы хотите скачать его сейчас?',
  'An error occurred while downloading the update. Please try again later.': 'При загрузке обновления произошла ошибка. Повторите попытку позже.',
  'You already have the newest version of {0}.': 'У вас уже установлена последняя версия {0}.',
  'An error occurred in retrieving update information. Please try again later.': 'Произошла ошибка при получении информации об обновлении. Повторите попытку позже.',
  'Downloading update...': 'Загружаем обновления...',
  'OK': 'Ок',
  'E-Mail': 'E-Mail',
  'Code': 'Код',
  'Cancel': 'Отмена',
  'Register': 'Регистрация',
  'Buy Now': 'Купить сейчас',
  'Please enter the registration information to upgrade trial version to registered version.': 'Пожалуйста, введите информацию о регистрации для обновления пробной версии до зарегистрированной.',
  'Invalid license!': 'Лицензия недействительна!',
  'The registration information must be entered exactly as they appear in your confirmation email. Using copy and paste method to enter the license is recommended.': 'Информацию о регистрации необходимо вводить точно так, как указано в электронном письме с подтверждением. Рекомендуем использовать копирование.',
  'You have successfully registration the program. Thank you for your support!': 'Вы успешно зарегистрировали программу. Спасибо за вашу поддержку!',
  'A new version of {0} is available': 'Доступна новая версия {0}',
  '{0} {1} is now available-you have {2}. Would you like to download it now?': '{0} {1} уже доступна - у вас установлена {2}. Хотите скачать сейчас?',
  'Skip This Version': 'Пропустить эту версию',
  'Remind Me Later': 'Напомнить позже',
  'Install Update': 'Установить обновление',
  'Software Update': 'Обновление программного обеспечения',
  'Release Notes': 'Примечания к выпуску:',
  'User name': 'Имя пользователя',
  'License to': 'Лицензия на',
  'About': 'О программе',
  'File': 'файл',
  'Show Log File': 'Показать файл журнала',
  'Edit': 'Редактировать',
  'Cut': 'Вырезать',
  'Copy': 'Копировать',
  'Paste': 'Вставить',
  'Select All': 'Выбрать все',
  'Window': 'Окно',
  'Minimize': 'Свернуть',
  'Zoom': 'Увеличить',
  'Preferences': 'Настройки',
  'Hide': 'Скрыть',
  'Hide Others': 'Скрыть другие',
  'Quit': 'Выход',
  'Help': 'Помощь',
  'Open Website': 'Открыть сайт',
  'Check for update': 'Проверить наличие обновлений',
  'regist successfully': 'регистрация завершена',
  'Change Account': 'Сменить аккаунт',
  'Please enter your new license,': 'Пожалуйста, введите вашу новую лицензию,',
  'or buy a new one.': 'или купите другую.',
  'Confirm': 'Подтвердить',
  'User ID': 'Идентификатор пользователя',
  'License Plan': 'Лицензионный план',
  'Change Plan': 'Изменить план',
  'Expiration Date': 'Срок действия',
  'Family license': 'Семейная лицензия',
  'One Year license': 'Лицензия на год',
  'Your license will expire soon on {0}. Please renew your license.': 'Срок действия вашей лицензии истекает {0}. Пожалуйста, продлите вашу лицензию.',
  'Renew License': 'Продлить лицензию',
  'Your license has expired. Please renew your license.': 'Срок действия вашей лицензии истек. Пожалуйста, продлите вашу лицензию.',
  'Your license has expired. Please renew your license or register with other license.':'Срок действия вашей лицензии истек. Пожалуйста, продлите вашу лицензию или зарегистрируйтесь, используя другую.',
  'Your license is valid until:': 'Ваша лицензия действительна до:'
}
